### ISSUE TITLE
KMeansClusterTest :  java.lang.RuntimeException: Main Dictionary not found!!!

### ISSUE THREAD

**Issue by SUTLFen** [sea-boat/TextAnalyzer#3]
when run KMeansClusterTest.java, the errors below occurs ,

```java
java.lang.RuntimeException: Main Dictionary not found!!!
	at org.wltea.analyzer.dic.Dictionary.loadMainDict(Dictionary.java:208)
	at org.wltea.analyzer.dic.Dictionary.<init>(Dictionary.java:68)
	at org.wltea.analyzer.dic.Dictionary.initial(Dictionary.java:83)
	at org.wltea.analyzer.core.IKSegmenter.init(IKSegmenter.java:87)
	at org.wltea.analyzer.core.IKSegmenter.<init>(IKSegmenter.java:65)
	at org.wltea.analyzer.lucene.IKTokenizer.<init>(IKTokenizer.java:67)
	at org.wltea.analyzer.lucene.IKAnalyzer.createComponents(IKAnalyzer.java:70)
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:198)
	at org.apache.lucene.document.Field.tokenStream(Field.java:570)
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:710)
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:417)
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:373)
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:231)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:478)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1575)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1320)
	at com.seaboat.text.analyzer.util.**VectorUtil.getVectorDimension**(VectorUtil.java:57)
	at com.seaboat.text.analyzer.clustering.KMeansCluster.learn(KMeansCluster.java:31)
	at com.seaboat.text.analyzer.clustering.KMeansClusterTest.testKMeans(KMeansClusterTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

It shows this sentence in VectorUtil.java does not work , 

```java
indexWriter.addDocument(doc);
```

 I google the answer for this , but cannot find anyone.  But I can try another method. 

 If you can figure out this problem above , please contact me.

**Comment by sea-boat** [comment]
it seems that there is something wrong with the path of Main Dictionary, you can try to debug the path.

**Comment by SUTLFen** [comment]
I have solved this problem. The reason is that the file "main2012.dic" and “quantifier.dic” do not exit in the class path after compiling.  you have to copy them from src\main\org\wltea\analyzer\dic  into the class path.

**Comment by sea-boat** [comment]
Cool!
